= LANCOM LCOS

OpenNMS configuration module to support monitoring for LANCOM devices with LCOS 9+ Firmware installed.
The configuration adds capabilities for SNMP Traps with varbindings and performance data collection for the following metrics:

- System load
- CPU usage in percent
- Memory usage in percent
- Internal temperature
- VPN statistics for peers and tunnels
- Mail statistics: buffered, sent and discarded

== Requirements

- LANCOM device with LCOS 9+ Firmware installed
- OpenNMS Meridian 2015+ or OpenNMS Horizon 14+
- Based on LANCOM LCOS MIB 9.20

== Installation

.Download and install from GitHub
[source, bash]
----
mkdir ${HOME}/opennms-config-workspace
cd ${HOME}/opennms-config-workspace
git clone https://github.com/opennms-config-modules/lancom-lcos.git
----

=== Events

.Install events
[source, bash]
----
cp ${HOME}/opennms-config-workspace/lancom-lcos/events/*.xml ${OPENNMS_HOME}/etc/events
----

.Include in eventconf.xml
[source, xml]
----
<event-file>events/lancom-lcos9.events.xml</event-file>
----

=== Data Collection

.Install datacollection configuration
[source, bash]
----
cp ${HOME}/opennms-config-workspace/lancom-lcos/datacollection/*.xml ${OPENNMS_HOME}/etc/datacollection
----

.Include in datacollection-config.xml
[source, xml]
----
<include-collection dataCollectionGroup="LANCOM-LCOS9"/>
----

=== Graph Report Definitions

.Install graph report definitions
[source, bash]
----
cp ${HOME}/opennms-config-workspace/lancom-lcos/graphs/*.properties ${OPENNMS_HOME}/etc/snmp-graph.properties.d
----
