# LANCOM LCOS 9

OpenNMS configuration module to support monitoring for LANCOM devices with LCOS 9+ Firmware installed.
The configuration adds capabilities for SNMP Traps with varbindings and performance data collection for the following metrics:

- System load
- CPU usage in percent
- Memory usage in percent
- Internal temperature
- VPN statistics for peers and tunnels
- Mail statistics: buffered, sent and discarded

## Requirements

- LANCOM device with LCOS 9+ Firmware installed
- OpenNMS Meridian 2015+ or OpenNMS Horizon 14+

## Download the configuration package

.Download the configuration files
[source, bash]
----
mkdir /tmp
cd /tmp
curl https://github.com/opennms-config-modules/lancom-lcos9/archive/lancom-lcos9-1.0.zip
unzip lancom-lcos9-1.0.zip
----

## Enable SNMP trap support

.Copy into OpenNMS configuration folders
[source, bash]
----
cp events/lancom-lcos9.events.xml ${OPENNMS_HOME}/etc/events
----

.Add include statement as first entry in ${OPENNMS_HOME}/etc/eventconf.xml
[source, bash]
----
<event-file>events/lancom-lcos9.events.xml</event-file>
----

## Enable performance data collection

[source, bash]
----
cp datacollection/lancom-lcos9.xml ${OPENNMS_HOME}/etc/datacollection
----

.Add include statement in alphabetical order in ${OPENNMS_HOME}/etc/datacollection-config.xml
[source, bash]
----
<include-collection dataCollectionGroup="LANCOM-LCOS9"/>
----

## Add performance graphs

[source, bash]
----
cp snmp-graph.properties.d/lancom-graph.properties ${OPENNMS_HOME}/etc/snmp-graph.properties.d/
----

# License & Authors

- Author:: Marcel Fuhrmann <fuhrmann@n3rd.org>

Licensed under the GNU Affero General Public License 3+. You may obtain a copy of the License at http://www.gnu.org/licenses/agpl-3.0.html.
