# LANCOM LCOS 9

OpenNMS configuration module to suppport monitoring for LANCOM devices with LCOS 9+ Firmware installed.
The configuration adds capabilities for SNMP Traps with varbindings and performance data collection for the following metrics:

- System load
- CPU usage in percent
- Memory usage in percent
- Internal temperature
- VPN statistics for peers and tunnels
- Mail statistics: buffered, sent and discarded

## Requirements

- LANCOM device with LCOS 9+ Firmware installed
- OpenNMS Meridian 2015+ or OpenNMS Horizon 14+

## Download the configuration package

.Download the configuration files
[source, bash]
----
curl URL-HERE 
----

## Enable SNMP trap support

.Copy into OpenNMS configuration folders
[source, bash]
----
copy events/lancom-lcos9.events.xml into ${OPENNMS_HOME}/etc/events
----

[source, bash]
----
add <event-file>events/lancom-lcos9.events.xml</event-file> entry in ${OPENNMS_HOME}/etc/eventconf.xml
----

## Enable performance data collection

[source, bash]
----
copy datacollection/lancom-lcos9.xml into ${OPENNMS_HOME}/etc/datacollection
----

[source, bash]
----
add <include-collection dataCollectionGroup="LANCOM-LCOS9"/> entry in ${OPENNMS_HOME}/etc/datacollection-config.xml
----

## Add performance graphs

[source, bash]
----
copy snmp-graphs.properties.d/lancom-graph.properties into ${OPENNMS_HOME}/etc/snmp-graph.properties.d/
----

# License & Authors

- Author:: Marcel Fuhrmann <fuhrmann@n3rd.org>

Licensed under the GNU Affero General Public License 3+. You may obtain a copy of the License at http://www.gnu.org/licenses/agpl-3.0.html.
